version: '3.1'

services:
    seoulair-data:
        container_name: seoulair-data
        restart: always
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - 5600:5600
            - 5601:5601
        links:
            - mongo

    mongo:
        container_name: dataDb
        image: mongo
        restart: always
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example
        ports:
          - 5602:27017
          
    mongo-express:
        image: mongo-express
        restart: always
        ports:
          - 5603:8081
        environment:
          ME_CONFIG_MONGODB_ADMINUSERNAME: root
          ME_CONFIG_MONGODB_ADMINPASSWORD: example
        depends_on:
          - mongo